version: '2'
services:
  # citus_master:
  #   image: 'citusdata/citus:5.2.1'
  #   ports: ['5432:5432']
  #   volumes: ['./citus:/etc/citus']

  # citus_worker_1:
  #   image: 'citusdata/citus:5.2.1'
  #   ports: ['5433:5432']

  # citus_worker_2:
  #   image: 'citusdata/citus:5.2.1'
  #   ports: ['5434:5432']


  # database
  postgres:
    build: ./postgres
    ports:
      - 5432:5432


  # migration services
  schemup_auth:
    image: tmtxt/schemup:v0.0.2


  # app services
  api_server:
    build: './api_server'
    ports: ['4000:4000']
    volumes: ['./api_server:/usr/src/app']
