# Create new auth user
POST http://127.0.0.1:4000/api/auth-users
Content-Type: application/json
dkcn-auth-token: 6ac999a3-f3af-41a8-bf25-6b610bd0b2e3

{
  "user_role": "admin",
  "username": "test14",
  "email": "test14",
  "password": "hello",
  "helloAbc": "def"
}

# Create admin user
POST http://127.0.0.1:4000/api/auth-users/admin
Content-Type: application/json

{
  "username": "admin",
  "email": "admin",
  "password": "admin"
}

# get_user
GET http://127.0.0.1:4000/api/auth-users

# login
POST http://127.0.0.1:4000/api/login
Content-Type: application/json

{
  "username": "test14",
  "password": "hello"
}
