# Create new auth user
POST http://127.0.0.1:4000/api/auth-users
Content-Type: application/json
dkcn-auth-token: 65ed0f9c-022c-4c16-8c88-3fdc409512ae

{
  "user_role": "admin",
  "username": "test14",
  "email": "test14",
  "password": "hello",
  "helloAbc": "def"
}

# Create admin user
POST http://127.0.0.1:4000/api/auth-users/admin
Content-Type: application/json

{
  "username": "admin",
  "email": "admin",
  "password": "admin"
}

# get_user
GET http://127.0.0.1:4000/api/auth-users

# login
POST http://127.0.0.1:4000/api/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
