# Create new auth user
POST http://127.0.0.1:4000/api/auth-users
Content-Type: application/json

{
  "username": "test2",
  "email": "test2",
  "password": "hello",
  "helloAbc": "def"
}

# get_user
GET http://127.0.0.1:4000/api/auth-users
